version: "3.9"

services:
  production:
    build:
      target: production
      context: .
    env_file:
      - .env
    ports:
      - "80:80"

  development:
    build:
      target: development
      context: .
      
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./todo_app
        target: /app/todo_app
    